import 'package:flutter/material.dart';

const String tileCacheName = 'map_cache';
const int daysBeforeAutoUpdate = 3;

const double mapMaxZoom = 18;
const double mapMinZoom = 12;
const double markerMinSize = 10;
const double fermataMarkerMinSize = 12;
const double markerMaxSize = 60;
const double fermataMarkerMaxSize = 20;
const int maxRoutesInMap = 4;
const maxHours = 4;
const maxHoursMap = 2;
const Color initialColor = Colors.teal;
const Map<int, String> ticketCodes = {
  // tickets
  712: 'Ordinario Urbano',
  714: 'City 100',
  715: 'Daily',
  716: 'Multidaily',
  //end tickets
};
const Map<int, String> subscriptionCodes = {
  2: 'Annuale Urbano 65 Piu\' Orario Ridotto',
  3: 'Annuale Urbano 65 Piu\' - Tariffa B',
  7: 'Junior',
  68: 'Mensile UNDER 26',
  72: 'Mensile Studenti Rete Urbana',
  101: 'Settimanale Formula 1',
  102: 'Settimanale Formula 2',
  103: 'Settimanale Formula 3',
  104: 'Settimanale Formula 4',
  105: 'Settimanale Formula 5',
  106: 'Settimanale Formula 6',
  107: 'Settimanale Formula 7',
  108: 'Settimanale Intera Area Formula',
  109: 'Settimanale FORMULA U',
  198: 'Mensile FORMULA U Sliding',
  199: 'Mensile Personale Rete Urbana (Formula U)',
  201: 'Mensile Formula 1',
  202: 'Mensile Formula 2',
  203: 'Mensile Formula 3',
  204: 'Mensile Formula 4',
  205: 'Mensile Formula 5',
  206: 'Mensile Formula 6',
  207: 'Mensile Formula 7',
  208: 'Mensile Intera Area Formula',
  261: 'Mensile Studenti Urbano+Suburbano',
  284: 'Biglietto 2 giorni',
  285: 'Biglietto 3 giorni',
  288: 'OLD Biglietto 2 giorni',
  289: 'OLD Biglietto 3 giorni',
  290: 'Mensile 65+ Urbano Orario Ridotto',
  291: 'Mensile 65+ Urbano',
  292: 'Semestrale Urbano Disoccupato over 20',
  299: 'Semestrale Urbano Disoccupato under 20',
  300: 'Corsa singola GTT a zone',
  301: 'Biglietto Multicorsa Extraurbano GTT',
  305: 'Settimanale O/D GTT Extraurbano',
  306: 'Mensile O/D GTT Extraurbano',
  307: 'Annuale Ivrea Rete Urbana e Dintorni',
  308: 'Annuale Extraurbano O/D',
  310: 'Plurimensile Studenti Extraurbano O/D',
  349: 'Annuale Anziani (over 65) rete Urbana Ivrea e Dintorni',
  350: 'Annuale Anziani (over 65) rete Urbana Ivrea e Dintorni B2',
  351: 'Annuale Anziani (over 65) rete Urbana Ivrea e Dintorni B3',
  352: 'Annuale Anziani (over 65) rete Urbana Ivrea e Dintorni B4',
  364: 'Biglietto rete Urbana Ivrea e Dintorni',
  365: 'Settimanale rete Urbana Ivrea e Dintorni',
  366: 'Mensile rete Urbana Ivrea e Dintorni',
  367: 'Plurimensile Studenti rete Urbana Ivrea e Dintorni',
  370: 'Carnet 5 corse rete Urbana Ivrea e Dintorni',
  371: 'Carnet 15 corse rete Urbana Ivrea e Dintorni',
  712: 'Biglietto Ordinario urbano SmarCard',
  714: 'OLD City su Smart Card',
  715: 'OLD Daily su smart card',
  716: 'OLD Multidaily su smart card',
  718: 'Multidaily su Smartphone',
  719: 'City su Smartphone',
  720: 'Daily su Smartphone',
  721: 'Annuale UNDER 26',
  722: 'Annuale UNDER 26 Fascia A',
  723: 'Annuale UNDER 26 Fascia B',
  724: 'Annuale UNDER 26 Fascia C',
  730: 'Mensile Over 65',
  731: 'Annuale Over 65 B',
  732: 'Annuale Over 65 C',
  733: 'Annuale Over 65 D',
  741: 'Mensile urbano agevolato cat.V-VI-VII-VIII',
  751: 'Semestrale Disoccupati',
  761: 'Annuale Over A',
  770: 'City su Smart Card',
  772: 'Daily su smart card',
  774: 'Multidaily su smart card',
  910: 'Annuale Urbano 65 Piu\' - Tariffa A',
  913: 'Annuale Comune di Torino - FERIALE',
  914: 'Annuale Comune di Torino - FESTIVO / SERALE',
  916: 'Pensionati Minimi INPS',
  920: 'Pensionati GTT',
  929: 'Tessera di servizio dipendente GTT',
  937: 'Categorie speciali',
  989: 'TRAMBUSTO SCUOLE MEDIE',
  991: 'TRAMBUSTO',
  992: 'Eventi speciali',
  993: 'Annuale FORMULA U',
  994: 'Abbonamenti speciali',
  4001: 'Settimanale Formula',
  4002: 'Mensile Formula',
  4003: 'Annuale Formula',
  4004: 'Plurimensile studenti Formula',
  4500: 'Annuale libera circolazione Regione Piemonte',
  4501: 'Annuale libera circolazione Reg Piem con accomp.',
  4502: 'Annuale operatore regionale',
  4505: 'Annuale FFAA OBBLIGO DI UNIFORME',
};
