// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx6GVMRtVBi5ZTFXTrABZa8JZD7S-Lrwc',
    appId: '1:102279235096:web:0ecb06b71ee860ff8f656d',
    messagingSenderId: '102279235096',
    projectId: 'gtt-app-40686',
    authDomain: 'gtt-app-40686.firebaseapp.com',
    storageBucket: 'gtt-app-40686.firebasestorage.app',
    measurementId: 'G-PDLBJEW9TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyxsdPXKsMcoHsGi19viMhDw39ZWWoXI',
    appId: '1:102279235096:android:af0323a220681d928f656d',
    messagingSenderId: '102279235096',
    projectId: 'gtt-app-40686',
    storageBucket: 'gtt-app-40686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_pcT3e4TK6AMRr1gIyWUbAKj8NE4AmH0',
    appId: '1:102279235096:ios:d844fd5c50999aeb8f656d',
    messagingSenderId: '102279235096',
    projectId: 'gtt-app-40686',
    storageBucket: 'gtt-app-40686.firebasestorage.app',
    iosBundleId: 'com.example.flutterGtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_pcT3e4TK6AMRr1gIyWUbAKj8NE4AmH0',
    appId: '1:102279235096:ios:d844fd5c50999aeb8f656d',
    messagingSenderId: '102279235096',
    projectId: 'gtt-app-40686',
    storageBucket: 'gtt-app-40686.firebasestorage.app',
    iosBundleId: 'com.example.flutterGtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx6GVMRtVBi5ZTFXTrABZa8JZD7S-Lrwc',
    appId: '1:102279235096:web:6db683bb7bc8d6d38f656d',
    messagingSenderId: '102279235096',
    projectId: 'gtt-app-40686',
    authDomain: 'gtt-app-40686.firebaseapp.com',
    storageBucket: 'gtt-app-40686.firebasestorage.app',
    measurementId: 'G-Y47W68SMCZ',
  );
}
